# Scheme name: Flatland
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming (https://github.com/tinted-theming)

"attribute" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string" = "base0B"
"type" = "base0A"
"variable" = "base08"
"variable.other.member" = "base0D"
"warning" = "base09"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading.1" = { fg = "base0D", modifiers = ["bold"] }
"markup.heading.2" = { fg = "base08", modifiers = ["bold"] }
"markup.heading.3" = { fg = "base09", modifiers = ["bold"] }
"markup.heading.4" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading.5" = { fg = "base0B", modifiers = ["bold"] }
"markup.heading.6" = { fg = "base0C", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { style = "curl" } }

"ui.background" = { bg = "base00" }
"ui.bufferline.active" = { fg = "base00", bg = "base03", modifiers = ["bold"] }
"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.cursor" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursorline.primary" = { fg = "base05", bg = "base01" }
"ui.cursor.match" = { fg = "base05", bg = "base02", modifiers = ["bold"] }
"ui.cursor.select" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base03", modifiers = ["reversed"] }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base05", bg = "base01" }
"ui.statusline.inactive" = { bg = "base01", fg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.normal" = { fg = "base00", bg = "base0C" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }
"ui.text" = "base05"
"ui.text.directory" = { fg = "base0D", modifiers = ["bold"] }
"ui.text.focus" = "base05"
"ui.virtual.indent-guide" = { fg = "base03" }
"ui.virtual.inlay-hint" = { fg = "base03" }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.jump-label" = { fg = "base0A", modifiers = ["bold"] }
"ui.window" = { bg = "base01" }

[palette]
base00 = "#1c1e20" # Default Background
base01 = "#1c1d19" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#1c1d19" # Selection Background
base03 = "#545552" # Comments, Invisibles, Line Highlighting
base04 = "#8d8e8b" # Dark Foreground (Used for status bars)
base05 = "#c5c6c4" # Default Foreground, Caret, Delimiters, Operators
base06 = "#fefffe" # Light Foreground (Not often used)
base07 = "#fefffe" # Light Background (Not often used)
base08 = "#f18238" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#f3ef6d" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#61b8d0" # Classes, Markup Bold, Search Text Background
base0B = "#9ed264" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#d53864" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#4f96be" # Functions, Methods, Attribute IDs, Headings
base0E = "#695abb" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#78411c" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
base10 = "#121310"
base11 = "#090908"
base12 = "#d12a24"
base13 = "#ff8948"
base14 = "#a7d32c"
base15 = "#d53864"
base16 = "#61b8d0"
base17 = "#695abb"
